name: CI .NET

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.12.x

    - name: Restore dependencies
      run: dotnet restore ExpensesManager

    - name: Install npm dependencies
      run: npm ci --prefix ./ExpensesManager/src/ExpensesManager.WebUI

    - name: Build Tailwind CSS
      run: npm run build:css --prefix ./ExpensesManager/src/ExpensesManager.WebUI

    - name: Build application
      run: dotnet build --no-restore --configuration Release ExpensesManager

    - name: Run unit tests
      run: dotnet test --no-build --configuration Release --verbosity normal ExpensesManager

    - name: Run code coverage
      run: |
        dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover